services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: ${ROS_DISTRO:-rolling}
    container_name: comau_dev
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    user: "${UID:-0}:${GID:-0}"
    volumes:
      - .:/ros2_ws/src:rw 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: bash -lc " sleep infinity"
