joint_state_broadcaster:
  # If 'joints' and/or 'interfaces' is left blank, all will be published in compiled URDF order.
  # Listing them explictly defines the order in the published message.
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    joints:
      - waist
      - shoulder
      - elbow_active
      - forearm_roll
      - wrist_angle
      - wrist_rotate
    interfaces:
      - position
      - velocity
      # - current
      - effort

position_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    interface_name: position
    joints:
      - waist
      - shoulder
      - elbow_active
      - forearm_roll
      - wrist_angle
      - wrist_rotate

velocity_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    interface_name: velocity
    joints:
      - waist
      - shoulder
      - elbow_active
      - forearm_roll
      - wrist_angle
      - wrist_rotate

acceleration_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    interface_name: acceleration
    joints:
      - waist
      - shoulder
      - elbow_active
      - forearm_roll
      - wrist_angle
      - wrist_rotate

current_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    interface_name: current
    joints:
      - waist
      - shoulder
      - elbow_active
      - forearm_roll
      - wrist_angle
      - wrist_rotate

effort_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    interface_name: effort
    joints:
      - waist
      - shoulder
      - elbow_active
      - forearm_roll
      - wrist_angle
      - wrist_rotate

joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - waist
      - shoulder
      - elbow_active
      - forearm_roll
      - wrist_angle
      - wrist_rotate
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

