controller_manager:
  ros__parameters:
    update_rate: 2500  # Hz
    enforce_command_limits: false # command limits are enforced by the driver itself
    # hardware_components_initial_state:
    #   inactive:
    #     - comau_nj_130_2_6

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: position_controllers/JointGroupPositionController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    acceleration_controller:
      type: forward_command_controller/ForwardCommandController

    current_controller:
      type: forward_command_controller/ForwardCommandController

    effort_controller:
      type: forward_command_controller/ForwardCommandController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


joint_state_broadcaster:
  # If 'joints' and/or 'interfaces' is left blank, all will be published in compiled URDF order.
  # Listing them explictly defines the order in the published message.
  ros__parameters:
    joints:
      - waist
      - shoulder
      - elbow_active
      - forearm_roll
      - wrist_angle
      - wrist_rotate
    interfaces:
      - position
      - velocity
      - current
      - effort

position_controller:
  ros__parameters:
    joints:
      - waist
      - shoulder
      - elbow_active
      - forearm_roll
      - wrist_angle
      - wrist_rotate

velocity_controller:
  ros__parameters:
    joints:
      # - waist
      # - shoulder
      # - elbow_active
      - forearm_roll
      - wrist_angle
      # - wrist_rotate

acceleration_controller:
  ros__parameters:
    joints:
      - waist
      - shoulder
      - elbow_active
      - forearm_roll
      - wrist_angle
      - wrist_rotate
    interface_name: acceleration

current_controller:
  ros__parameters:
    joints:
      - waist
      - shoulder
      - elbow_active
      - forearm_roll
      - wrist_angle
      - wrist_rotate
    interface_name: current

effort_controller:      
  ros__parameters:
    joints:
      - waist
      - shoulder
      - elbow_active
      - forearm_roll
      - wrist_angle
      - wrist_rotate
    interface_name: effort 

joint_trajectory_controller:
  ros__parameters:
    joints:
      - waist
      - shoulder
      - elbow_active
      - forearm_roll
      - wrist_angle
      - wrist_rotate