name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build (rolling in ros:rolling)
    runs-on: ubuntu-24.04
    container:
      image: ros:rolling

    env:
      ROS_DISTRO: rolling
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update system
        run: |
          apt-get update
          apt-get upgrade -y

      - name: Install CRCOpen ORLDriver
        run: |
          apt-get install -y ./crcopen_hardware/lib/orl_driver-*.deb

      - name: Install dependencies
        run: |
          rosdep update
          rosdep install --from-paths . -y --ignore-src

      - name: Build the driver
        shell: bash
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          colcon build
